services:
  - type: web
    name: student-course-registration
    env: static
    buildCommand: export NODE_OPTIONS=--openssl-legacy-provider && npm run install-client && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16.20.0 